### ISSUE TITLE
Random Observations

### ISSUE THREAD

**Issue by ldo** [MSLNZ/Quantity-Value#1]
Hi. Not sure if this is the sort of feedback you were after, but here goes.

I appreciate from your [introduction](https://quantity-value.readthedocs.io/en/stable/introduction.html) that you are trying to go beyond mere dimensional analysis, to draw a distinction between different measurements that, while their dimensions might appear to match, should not be considered commensurate. But I think there is a limit to how far such rules can be used to ensure physical calculations remain meaningful—at some point, you have to look at the actual physics behind the formulas.

For example, you seem to suggest that fuel consumption having the dimensions of area is somehow an “ambiguity” or “difficulty of expression”. It’s not: it has a perfectly valid physical meaning. If you take the volume of fuel consumed by a vehicle during a journey and conceptually stretch it out as a long, thin prism covering the length of the route, then the cross-sectional area at any point can be set to represent the instantaneous fuel consumption at that point; integrate that area over the entire route, and you get the volume of the prism, which is the total fuel consumed.

For example, a figure of 8l/100km translates to a cross-sectional area of (8 × 1000 mm<sup>3</sup>) ÷ (100 × 1000 × 1000 mm) = 80 × 10<sup>-6</sup> mm<sup>2</sup> = 80 µm<sup>2</sup>.

Related to this, it has seemed to me that “litres per 100 km” is a bit of mouthful; it seems easier to re-express the unit as cl/km. This gives exactly the same numbers, so no conversion is required, so it makes sense for any unit-checking system to accept one in place of the other. The usage may confuse motoring journalists, but physicists and engineers should be able to take it in their stride.

Another example you mention is the need to distinguish between torque and energy, both of which have units of force times distance. However, it is worth noting that torque is a vector quantity, being a cross product of the force and the length of a lever arm, while energy is a scalar, being a dot product of a force and the distance over which it acts. Nothing has to move for a torque to be exerted, whereas energy is only transferred when movement takes place. This is the kind of distinction that cannot be conveyed by any unit system, ultimately you have to appeal to the underlying physics to decide whether a formula makes sense or not.

## [Angles](https://quantity-value.readthedocs.io/en/stable/examples.html#angles) ##

Here I see you try to explicitly introduce an angle unit to avoid direct commensurateness between angles and ratios of distances. But there are situations where such commensurateness is entirely appropriate. For example, the approximation

$$x \approx \sin x$$

holds more and more accurately for $x$ closer and closer to zero, so substituting the former for the latter is commonly done in calculations in such cases. If you insist on $x$ having angle units, does that mean $\sin x$ has to have those units too? Then what happens to the Euler identity

$$e^{ix} = \cos x + i \sin x$$

Does that mean that the result of raising $e$ to a power must also have angle units?

Even if you insist that both $\cos x$ and $\sin x$ have angle units, then

$$\tan x = {\sin x \over \cos x}$$

still ends up as a pure ratio. But we also have the approximation

$$x \approx \tan x$$

for $x$ close to zero (since in this case $\cos x \approx 1$). So now we must introduce the angle-unit factor into common formulas all over the place. I suspect this will get unwieldy pretty quickly.

## Conclusion ##

In your introduction, you wonder why this problem has not already been addressed. Maybe it has: but previous attempts have all run into the same limitations: too much pain for too little gain.

The infamous Mars Climate Orbiter failure wasn’t caused by inappropriate unit dimensions, but by inappropriate unit conversion factors. For example, there should be no problem adding a linear distance in inches to one in metres; given that an inch is defined as 0.0254m anyway, the conversion to a common unit is straightforward. The Mars Climate Orbiter was lost because one group thought a number was in one unit while another thought it was actually in another, and so a conversion factor was wrong.

Looking at the “[Gimli Glider](https://en.wikipedia.org/wiki/Gimli_Glider)” incident, the problem came about because of an unfortunate coincidence of more than one failure. It wasn’t just the fuel being measured in the wrong units, it was also the fuel gauges being inoperative; if they had been working, the crew should have noticed the insufficiency of fuel much earlier. Safety relies on not just one thing being done right, but on _everything_ being done right.

**Comment by BlairDHall** [comment]
Thank you for posting your thoughts Ido.

I think the intention of raising 'issues' on github is probably to draw attention to aspects of the software that could be improved. However, your random thoughts are sensible observations. Even though they do not raise an issue, except perhaps to suggest that, in your opinion, our project has no merit. 

I agree with the basic factual content of your message, but not with the conclusions you draw. However, this is not the right place to debate the merits of "too much pain for too little gain", as you put it. 

Let me just say that we went into this project with a clear understanding of the sorts of issue that you mention. Our intention is to develop general purpose software support for quantities, not to extend applied mathematics or physics techniques. Rather than going "beyond" dimensional analysis, we are trying to make better use of notions from dimensional analysis and quantity calculus. 

I might also add that it is a well-established fact that including angle as a base quantity in the SI would lift the ambiguity between torque and energy. However, to do so is deemed too disruptive: no one is advocating for it. On the other hand, software like ours can adopt the exta dimension "under the hood" so to speak, without distracting users too much. A number of authors have already suggested that this is an idea worth considering.

Our work was to have been discussed at international conferences in Europe later in the year. Covid-19 will now delay that, but we will have those discussions sooner or later.

Thank you again for your interest.

**Comment by BlairDHall** [comment]
I am going to close this now, because this does not require further attention.
